INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [29/Apr/2019 11:40:10] "GET /api/v1.0/v1.0/index HTTP/1.1" 404 -
INFO _internal.py:122 127.0.0.1 - - [29/Apr/2019 11:40:20] "GET /api/v1.0/v1.0/index HTTP/1.1" 404 -
ERROR demo.py:8 xxx严重错误
WARNING demo.py:9 警告
INFO demo.py:10 info
DEBUG demo.py:11 debug
INFO _internal.py:122 127.0.0.1 - - [29/Apr/2019 11:40:26] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR demo.py:8 xxx严重错误
WARNING demo.py:9 警告
INFO demo.py:10 info
DEBUG demo.py:11 debug
INFO _internal.py:122 127.0.0.1 - - [29/Apr/2019 11:41:57] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR demo.py:8 xxx严重错误
WARNING demo.py:9 警告
INFO demo.py:10 info
DEBUG demo.py:11 debug
INFO _internal.py:122 127.0.0.1 - - [29/Apr/2019 11:41:58] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [29/Apr/2019 11:48:43] "POST /findByAddressEntBasic HTTP/1.1" 404 -
ERROR demo.py:8 xxx严重错误
WARNING demo.py:9 警告
INFO demo.py:10 info
DEBUG demo.py:11 debug
INFO _internal.py:122 127.0.0.1 - - [29/Apr/2019 12:32:51] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR demo.py:8 xxx严重错误
WARNING demo.py:9 警告
INFO demo.py:10 info
DEBUG demo.py:11 debug
INFO _internal.py:122 127.0.0.1 - - [29/Apr/2019 15:03:42] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR demo.py:8 xxx严重错误
WARNING demo.py:9 警告
INFO _internal.py:122 127.0.0.1 - - [29/Apr/2019 15:04:12] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR __init__.py:97 Error: Directory migrations already exists
INFO _internal.py:122  * Restarting with stat
WARNING _internal.py:122  * Debugger is active!
INFO _internal.py:122  * Debugger PIN: 158-954-805
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR __init__.py:97 Error: Directory migrations already exists
ERROR __init__.py:97 Error: Directory migrations already exists
INFO _internal.py:122  * Restarting with stat
WARNING _internal.py:122  * Debugger is active!
INFO _internal.py:122  * Debugger PIN: 158-954-805
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 14:07:05] "GET /18385855845?image_code=1 HTTP/1.1" 404 -
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 14:07:05] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 14:07:22] "GET /sms_codes/18385855845?image_code=1 HTTP/1.1" 404 -
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 14:07:42] "GET /api/v1.0/sms_codes/18385855845?image_code=1 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 14:09:02] "GET /api/v1.0/image_codes/1 HTTP/1.1" 500 -
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 14:09:02] "GET /api/v1.0/image_codes/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 14:09:02] "GET /api/v1.0/image_codes/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 14:09:02] "GET /api/v1.0/image_codes/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 14:09:02] "GET /api/v1.0/image_codes/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 14:09:02] "GET /api/v1.0/image_codes/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 14:09:02] "GET /api/v1.0/image_codes/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:122  * Detected change in 'E:\\datum\\ihome_demo\\ihome\\api_1_0\\verify_code.py', reloading
INFO _internal.py:122  * Restarting with stat
WARNING _internal.py:122  * Debugger is active!
INFO _internal.py:122  * Debugger PIN: 158-954-805
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122  * Detected change in 'E:\\datum\\ihome_demo\\ihome\\constants.py', reloading
INFO _internal.py:122  * Restarting with stat
WARNING _internal.py:122  * Debugger is active!
INFO _internal.py:122  * Debugger PIN: 158-954-805
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122  * Detected change in 'E:\\datum\\ihome_demo\\ihome\\api_1_0\\verify_code.py', reloading
INFO _internal.py:122  * Restarting with stat
WARNING _internal.py:122  * Debugger is active!
INFO _internal.py:122  * Debugger PIN: 158-954-805
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122  * Detected change in 'E:\\datum\\ihome_demo\\ihome\\api_1_0\\verify_code.py', reloading
INFO _internal.py:122  * Restarting with stat
WARNING _internal.py:122  * Debugger is active!
INFO _internal.py:122  * Debugger PIN: 158-954-805
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 15:53:32] "POST /findRealtimeEntBasic/notes HTTP/1.1" 404 -
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 15:53:37] "POST /findRealtimeEntBasic/notes HTTP/1.1" 404 -
INFO _internal.py:122 127.0.0.1 - - [17/May/2019 15:53:51] "POST /findRealtimeEntBasic/notes HTTP/1.1" 404 -
